version: '3.8'
services:
  db:
    image: postgres:13.7-alpine
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - TZ=Europe/Moscow

  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - SERVER_PORT=8080
      - SHAREIT_SERVER_URL=http://server:9090
      - TZ=Europe/Moscow

  server:
    build: ./server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - TZ=Europe/Moscow